micronaut:
  application:
    name: nossaCadaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update

cep.host: https://viacep.com.br/ws/
